# Generated by Django 6.1.1 on 2026-09-24 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_server_ip', models.CharField(default='192.168.0.122', max_length=100)),
                ('db_port', models.IntegerField(default=1433)),
                ('db_name', models.CharField(default='INDIA_FLOOR_KY1', max_length=100)),
                ('db_username', models.CharField(default='sa', max_length=100)),
                ('db_password', models.CharField(default='••••••••', max_length=100)),
                ('scanner_sim_enabled', models.BooleanField(default=True)),
                ('plc_sim_enabled', models.BooleanField(default=True)),
                ('screw_sim_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=1)),
                ('check_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_name', models.CharField(default='kia_console_assembly.png', max_length=100)),
                ('before_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_processes', to='floor_app.process')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProcessField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('select', 'Dropdown Select'), ('number', 'Number Input')], default='select', max_length=20)),
                ('sequence', models.IntegerField(default=1)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='floor_app.process')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('car_type', models.CharField(default='MQ4i', max_length=50)),
                ('alc', models.CharField(default='B81V', max_length=50)),
                ('part_no', models.CharField(default='84605-GB810FHV', max_length=100)),
                ('lot_no', models.CharField(default='LOT20260924-01', max_length=50)),
                ('order_qty', models.IntegerField(default=120)),
                ('production_qty', models.IntegerField(default=42)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed / NG')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor_app.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='001', max_length=50)),
                ('result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('options_data', models.JSONField(default=dict)),
                ('subparts_data', models.JSONField(default=list)),
                ('screws_data', models.JSONField(default=list)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('rework_mode', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_app.process')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='floor_app.productionunit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
