# Generated by Django 6.1.1 on 2026-09-24 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('operator_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('OPERATOR', 'Station Operator')], default='OPERATOR', max_length=20)),
                ('station_code', models.CharField(default='ST-01', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor_app.process')),
            ],
            options={
                'ordering': ['role', 'operator_id'],
            },
        ),
    ]
