# Generated by Django 6.1.1 on 2026-09-24 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0002_operatoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=50)),
                ('car_type', models.CharField(default='MQ4i', max_length=50)),
                ('alc', models.CharField(default='B81V', max_length=50)),
                ('part_no', models.CharField(default='84605-GB810FHV', max_length=100)),
                ('lot_no', models.CharField(default='LOT20260924-01', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor_app.operatoruser')),
                ('current_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor_app.process')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
