# Generated by Django 6.1.1 on 2026-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0003_productionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatoruser',
            name='password_text',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
